# Generated by Django 4.0.6 on 2022-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bg', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=50)),
            ],
        ),
    ]
